name: impostor_v2
description: El Impostor — juego de fiesta por turnos.
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#161616"
  adaptive_icon_foreground: "assets/icon/app_icon_foreground.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon_foreground.png"
    background_color: "#161616"
    theme_color: "#D95F38"

flutter:
  uses-material-design: true

