const Map<String, Map<String, String>> kLocalizations = {
  'es': {
    'app_title': 'CHAMELEON',
    'app_subtitle': 'Juego de deducción y mentiras',
    'play': 'Jugar',
    'rules_title': 'Cómo Jugar',
    'rules_step_1': 'Decide cuántos jugadores e impostores seréis. Se os asignará una categoría.',
    'rules_step_2': 'Pasad el dispositivo. Cada uno verá el rol y, si es ciudadano, la palabra secreta.',
    'rules_step_3': '¡A debatir! Cada jugador dice una palabra relacionada. El camaleón debe disimular.',
    'rules_step_4': 'Votación y resultado. ¿Encontraréis al camaleón antes de que sea tarde?',
    'rules_close': 'Entendido',
    'players': 'Jugadores',
    'impostors': 'Impostores',
    'names_title': 'NOMBRES',
    'names_subtitle': 'Escribe los nombres del grupo',
    'category': 'CATEGORÍA',
    'round_time': 'TIEMPO DE RONDA',
    'clues_toggle': 'Pistas para el impostor',
    'clues_toggle_subtitle': 'El impostor puede ver una pista sobre la palabra secreta.',
    'validation_msg': 'Mínimo 3 jugadores y menos impostores que jugadores.',
    'start': '¡Empezar!',
    'round_label': 'RONDA',
    'pass_phone_to': 'Pasa el móvil a',
    'turn_progress': 'Turno {current} de {total}',
    'others_look_away': 'Que el resto mire para otro lado.',
    'see_my_card': 'Ver mi carta',
    'start_round': 'Comenzar ronda',
    'hide_and_pass': 'Ocultar y pasar',
    'tap_to_see_card': 'Toca para ver tu carta',
    'wait_grace': 'Espera…',
    'role_chameleon': 'CAMALEÓN',
    'role_citizen': 'CIUDADANO',
    'chameleon_hint': 'No tienes palabra.\nDescúbrela tú.',
    'citizen_hint': '¡Eres ciudadano!\nNo reveles tu palabra.',
    'clue_reveal_btn': 'Ver pista',
    'clue_label': 'Pista: {clue}',
    'timer_title': 'DISCUSIÓN',
    'timer_paused': 'EN PAUSA',
    'timer_running': 'DEBATID',
    'time_up': '¡Tiempo!',
    'vote_btn': '¡A votar!',
    'vote_title': 'VOTACIÓN',
    'vote_subtitle': '¿Quién es el impostor?',
    'vote_question': '¿Quién está mintiendo?',
    'eliminate_player': 'Eliminar a {name}',
    'select_suspect': 'Selecciona un sospechoso',
    'result_title_won': '¡Era el impostor!',
    'result_title_lost': '¡Se salvó el impostor!',
    'result_sub_won': 'Los ciudadanos han ganado esta ronda.',
    'result_sub_lost': 'El impostor sigue entre vosotros…',
    'result_sub_impostor_won': '¡El impostor ha ganado la partida!',
    'era_chameleon': 'ERA EL IMPOSTOR',
    'era_citizen': 'ERA CIUDADANO',
    'secret_word_was': 'La palabra era',
    'remaining_chameleons': 'Impostores restantes',
    'next_round': 'Siguiente ronda',
    'new_game': 'Nueva partida',
    'finish_game': 'Fin de partida',
    'play_again': 'Jugar de nuevo',
    'rounds_played': 'Rondas jugadas',
    'chameleon_was': 'El impostor era',
    'chameleons_were': 'Los impostores eran',
    'the_secret_word': 'La palabra secreta',
    'exit_options_title': 'Opciones de partida',
    'exit_options_sub': 'La partida continúa hasta que salgas.',
    'view_config': 'Ver configuración',
    'abandon_game': 'Abandonar la partida',
    'continue_playing': 'Continuar jugando',
    'config_title': 'Configuración',
    'time_label': 'Tiempo',
    'close': 'Cerrar',
    'default_player_prefix': 'Jugador',
    // Categories
    'cat_general': 'General',
    'cat_cine': 'Cine',
    'cat_comida': 'Comida',
    'cat_animales': 'Animales',
    'cat_deportes': 'Deportes',
    'cat_lugares': 'Lugares',
  },
  'en': {
    'app_title': 'CHAMELEON',
    'app_subtitle': 'A game of deduction and lies',
    'play': 'Play',
    'rules_title': 'How to Play',
    'rules_step_1': 'Decide how many players and chameleons you will be. A category will be assigned.',
    'rules_step_2': 'Pass the device. Each player will see their role, and if they are a citizen, the secret word.',
    'rules_step_3': 'Let\'s debate! Each player says one related word. The chameleon must blend in.',
    'rules_step_4': 'Vote and result. Will you find the chameleon before it\'s too late?',
    'rules_close': 'Got it',
    'players': 'Players',
    'impostors': 'Chameleons',
    'names_title': 'NAMES',
    'names_subtitle': 'Write group names',
    'category': 'CATEGORY',
    'round_time': 'ROUND TIME',
    'clues_toggle': 'Clues for the chameleon',
    'clues_toggle_subtitle': 'The chameleon can see a clue about the secret word.',
    'validation_msg': 'Minimum 3 players, and fewer chameleons than players.',
    'start': 'Start!',
    'round_label': 'ROUND',
    'pass_phone_to': 'Pass the phone to',
    'turn_progress': 'Turn {current} of {total}',
    'others_look_away': 'Everyone else look away.',
    'see_my_card': 'See my card',
    'start_round': 'Start round',
    'hide_and_pass': 'Hide & pass',
    'tap_to_see_card': 'Tap to see your card',
    'wait_grace': 'Wait…',
    'role_chameleon': 'CHAMELEON',
    'role_citizen': 'CITIZEN',
    'chameleon_hint': 'You have no word.\nFigure it out yourself.',
    'citizen_hint': 'You are a citizen!\nDo not reveal your word.',
    'clue_reveal_btn': 'See clue',
    'clue_label': 'Clue: {clue}',
    'timer_title': 'DISCUSSION',
    'timer_paused': 'PAUSED',
    'timer_running': 'DEBATE',
    'time_up': 'Time\'s up!',
    'vote_btn': 'Go to vote!',
    'vote_title': 'VOTING',
    'vote_subtitle': 'Who is the chameleon?',
    'vote_question': 'Who is lying?',
    'eliminate_player': 'Eliminate {name}',
    'select_suspect': 'Select a suspect',
    'result_title_won': 'It was the chameleon!',
    'result_title_lost': 'The chameleon survived!',
    'result_sub_won': 'Citizens won this round.',
    'result_sub_lost': 'The chameleon is still among you…',
    'result_sub_impostor_won': 'The chameleon won the game!',
    'era_chameleon': 'WAS THE CHAMELEON',
    'era_citizen': 'WAS A CITIZEN',
    'secret_word_was': 'The word was',
    'remaining_chameleons': 'Chameleons remaining',
    'next_round': 'Next round',
    'new_game': 'New game',
    'finish_game': 'End game',
    'play_again': 'Play again',
    'rounds_played': 'Rounds played',
    'chameleon_was': 'The chameleon was',
    'chameleons_were': 'The chameleons were',
    'the_secret_word': 'The secret word',
    'exit_options_title': 'Game Options',
    'exit_options_sub': 'The game continues until you exit.',
    'view_config': 'View config',
    'abandon_game': 'Abandon game',
    'continue_playing': 'Continue playing',
    'config_title': 'Configuration',
    'time_label': 'Time',
    'close': 'Close',
    'default_player_prefix': 'Player',
    // Categories
    'cat_general': 'General',
    'cat_cine': 'Cinema',
    'cat_comida': 'Food',
    'cat_animales': 'Animals',
    'cat_deportes': 'Sports',
    'cat_lugares': 'Places',
  },
  'de': {
    'app_title': 'CHAMELEON',
    'app_subtitle': 'Ein Spiel der Deduktion und Lügen',
    'play': 'Spielen',
    'rules_title': 'Spielregeln',
    'rules_step_1': 'Entscheidet, wie viele Spieler und Chamäleons ihr sein wollt. Eine Kategorie wird zugewiesen.',
    'rules_step_2': 'Gebt das Gerät weiter. Jeder sieht seine Rolle und, wenn er ein Bürger ist, das geheime Wort.',
    'rules_step_3': 'Lasst uns diskutieren! Jeder sagt ein verwandtes Wort. Das Chamäleon muss sich anpassen.',
    'rules_step_4': 'Abstimmung und Ergebnis. Findet ihr das Chamäleon, bevor es zu spät ist?',
    'rules_close': 'Verstanden',
    'players': 'Spieler',
    'impostors': 'Chamäleons',
    'names_title': 'NAMEN',
    'names_subtitle': 'Schreibe die Namen der Gruppe',
    'category': 'KATEGORIE',
    'round_time': 'RUNDENZEIT',
    'clues_toggle': 'Hinweise für das Chamäleon',
    'clues_toggle_subtitle': 'Das Chamäleon kann einen Hinweis auf das geheime Wort sehen.',
    'validation_msg': 'Mindestens 3 Spieler und weniger Chamäleons als Spieler.',
    'start': 'Starten!',
    'round_label': 'RUNDE',
    'pass_phone_to': 'Gib das Handy an',
    'turn_progress': 'Zug {current} von {total}',
    'others_look_away': 'Alle anderen wegschauen.',
    'see_my_card': 'Meine Karte sehen',
    'start_round': 'Runde starten',
    'hide_and_pass': 'Verbergen & weitergeben',
    'tap_to_see_card': 'Tippen, um Karte to sehen',
    'wait_grace': 'Warten…',
    'role_chameleon': 'CHAMÄLEON',
    'role_citizen': 'BÜRGER',
    'chameleon_hint': 'Du hast kein Wort.\nFinde es selbst heraus.',
    'citizen_hint': 'Du bist Bürger!\nVerrate dein Wort nicht.',
    'clue_reveal_btn': 'Hinweis sehen',
    'clue_label': 'Hinweis: {clue}',
    'timer_title': 'DISKUSSION',
    'timer_paused': 'PAUSIERT',
    'timer_running': 'DISKUSSION',
    'time_up': 'Zeit abgelaufen!',
    'vote_btn': 'Zur Abstimmung!',
    'vote_title': 'ABSTIMMUNG',
    'vote_subtitle': 'Wer ist das Chamäleon?',
    'vote_question': 'Wer lügt?',
    'eliminate_player': '{name} eliminieren',
    'select_suspect': 'Wähle einen Verdächtigen',
    'result_title_won': 'Es war das Chamäleon!',
    'result_title_lost': 'Das Chamäleon hat überlebt!',
    'result_sub_won': 'Die Bürger haben diese Runde gewonnen.',
    'result_sub_lost': 'Das Chamäleon ist immer noch unter euch…',
    'result_sub_impostor_won': 'Das Chamäleon hat das Spiel gewonnen!',
    'era_chameleon': 'WAR DAS CHAMÄLEON',
    'era_citizen': 'WAR BÜRGER',
    'secret_word_was': 'Das Wort war',
    'remaining_chameleons': 'Verbleibende Chamäleons',
    'next_round': 'Nächste Runde',
    'new_game': 'Neues Spiel',
    'finish_game': 'Spiel beenden',
    'play_again': 'Nochmal spielen',
    'rounds_played': 'Gespielte Runden',
    'chameleon_was': 'Das Chamäleon war',
    'chameleons_were': 'Die Chamäleons waren',
    'the_secret_word': 'Das geheime Wort',
    'exit_options_title': 'Spieloptionen',
    'exit_options_sub': 'Das Spiel wird fortgesetzt, bis du es verlässt.',
    'view_config': 'Einstellungen anzeigen',
    'abandon_game': 'Spiel verlassen',
    'continue_playing': 'Weiterspielen',
    'config_title': 'Einstellungen',
    'time_label': 'Zeit',
    'close': 'Schließen',
    'default_player_prefix': 'Spieler',
    // Categories
    'cat_general': 'Allgemein',
    'cat_cine': 'Kino',
    'cat_comida': 'Essen',
    'cat_animales': 'Tiere',
    'cat_deportes': 'Sport',
    'cat_lugares': 'Orte',
  },
};

String translateWith(String currentLang, String key, [Map<String, String>? args]) {
  String text = kLocalizations[currentLang]?[key] ?? kLocalizations['en']?[key] ?? key;
  if (args != null) {
    args.forEach((k, v) {
      text = text.replaceAll('{$k}', v);
    });
  }
  return text;
}
